SOURCES = {"san jose mercury news (california)":"san jose mercury news", 
  "new york times blogs (the 6th floor)":"new york times", 
  "new york times blogs (artsbeat)":"new york times", 
  "new york times blogs (t magazine)":"new york times", 
  "new york times blogs (goal)":"new york times", 
  "new york times blogs (economix)":"new york times", 
  "denver post":"denver post", 
  "new york times blogs (at war)":"new york times", 
  "new york times blogs":"new york times", 
  "new york times blogs (media decoder)":"new york times", 
  "new york times blogs (lens)":"new york times", 
  "new york times blogs (the new old age)":"new york times", 
  "washington post":"washington post", 
  "new york times blogs (city room)":"new york times", 
  "usa today":"usa today", 
  "new york times blogs (latitude)":"new york times", 
  "denver post the denver post":"denver post", 
  "new york times blogs (iht rendezvous)":"new york times", 
  "new york times blogs (the public editor's journal)":"new york times", 
  "new york times blogs (in transit)":"new york times", 
  "new york times blogs (carpetbagger)":"new york times", 
  "new york times blogs (the fifth down)":"new york times", 
  "saint paul pioneer press (minnesota)":"saint paul pioneer press", 
  "new york times blogs (dealbook)":"new york times", 
  "st. paul pioneer press (minnesota)":"saint paul pioneer press", 
  "st. petersburg times (florida)":"st. petersburg times", 
  "washingtonpost.com":"washington post", 
  "new york times blogs (motherlode)":"new york times", 
  "new york times blogs (the caucus)":"new york times", 
  "new york times blogs (the loyal opposition)":"new york times", 
  "new york times blogs (opinionator)":"new york times", 
  "new york times blogs (taking note)":"new york times", 
  "new york times blogs (bill keller)":"new york times", 
  "tampa bay times":"tampa bay times", 
  "herald-sun (durham, n.c.)":"herald-sun", 
  "new york times blogs (bits)":"new york times", 
  "philadelphia inquirer":"philadelphia inquirer", 
  "chapel hill herald (durham, nc)":"chapel hill herald", 
  "atlanta journal and constitution":"atlanta journal and constitution", 
  "daily news (new york)":"daily news", 
  "new york times blogs (well)":"new york times", 
  "st. louis post-dispatch (missouri)":"st. louis post-dispatch", 
  "new york times blogs (green)":"new york times", 
  "new york times blogs (ross douthat)":"new york times", 
  "new york times blogs (you're the boss)":"new york times", 
  "new york times blogs (the choice)":"new york times", 
  "new york times blogs (diner's journal)":"new york times", 
  "herald-sun":"herald-sun", 
  "washington post blogs the fact checker":"washington post", 
  "new york times blogs (the lede)":"new york times", 
  "new york times blogs (fivethirtyeight)":"new york times", 
  "washington post blogs election 2012":"washington post", 
  "palm beach post (florida)":"palm beach post", 
  "new york times blogs (campaign stops)":"new york times", 
  "washington post blogs the fix":"washington post", 
  "new york times blogs (the learning network)":"new york times", 
  "new york times blogs (india ink)":"new york times", 
  "atlanta journal-constitution":"atlanta journal and constitution", 
  "herald-sun (durham, nc)":"herald-sun", 
  "new york times":"new york times",    
  "washington posts":"washington post",
  "raleigh extra (durham, nc)":"raleigh extra",
  "new york times blogs (prescriptions)":"new york times",
  "new york times blogs (mark bittman)":"new york times",
  "new york times blogs (straight sets)":"new york times",
  "new york times blogs (bucks)":"new york times",
  "new york times blogs (2012 london olympics)":"new york times",
  "new york times blogs (wheels)":"new york times",
  "new york times blogs (frank bruni)":"new york times",
  "washington post blogs the federal eye":"washington post",
  "washington post blogs in the loop":"washington post",
  "washington post blogs she the people":"washington post",
  "new york times blogs (nicholas d. kristof)":"new york times",
  "new york times blogs (paul krugman)":"new york times",
  "new york times blogs (dot earth)": "new york times",
  "new york times blogs (sinosphere)": "new york times",
  "new york times blogs (first draft)": "new york times",
  "washington post blogs": "washington post",
  "washington post blogs the plum line": "washington post",
  "washington post blogs the answer sheet": "washington post",
  "washington post blogs right turn": "washington post",
  "washington post blogs compost::compost::": "washington post",
  "washington post blogs erik wemple": "washington post",
  "washington post blogs achenblog::achenblog::": "washington post",
  "the denver post": "denver post",
  "san mateo county times (san mateo, ca)": "san jose mercury news",
  "mercury news (california)": "san jose mercury news",
  "new york times blogs (scientist at work)": "new york times",
  "new york times blogs (wordplay)": "new york times",
  "new york times blogs (joe nocera)": "new york times",
  "new york times blogs (op-talk)": "new york times",
  "new york times blogs (times insider)": "new york times",
  "new york times blogs (united nations general assembly)": "new york times",
  "new york times blogs (the new york times news minute)": "new york times",
  "the atlanta journal-constitution": "atlanta journal and constitution",
  "palm beach post (florida) florida)": "palm beach post"
  }
